spring:
  jpa:
   properties:
    hibernate:
    ddl-auto: update
    show-sql: true
    format-sql: true
  main:
    allow-circular-references: true
    
  datasource:
    url: jdbc:mysql://localhost:3306/spring-security
    username: root
    password: 
    driver-class-name: com.mysql.cj.jdbc.Driver

    
 